### ISSUE TITLE
Búsqueda información adicional - Debt Process

### ISSUE THREAD

**Issue by Joaquin-GM** [Joaquin-GM/GII_O_MA_19.07-Comparador-de-metricas-de-evolucion-en-repositorios-Software#12]

**Comment by Joaquin-GM** [comment]
Referencias para información:

- https://www.inf.usi.ch/jazayeri/docs/Thesis_Jacek_Ratzinger.pdf
- https://github.com/ossf/criticality_score

- https://linearb.io/blog/dora-engineering-metrics/
- https://github.com/DaGrisa/agile-metrics

Referencias adicionales:
-  https://aida.mitre.org/agile/agile-metrics/
- https://www.atlassian.com/agile/project-management/metrics
- https://www.infoq.com/articles/devops-maturity-metrics/
- https://sourcelevel.io/blog/top-10-agile-and-engineering-metrics-that-makes-sense-when-dealing-with-software-teams

**Comment by clopezno** [comment]
Creo que es un buen conjunto de herramientas. Nos serviran para poder comparar la  funcionalidad de nuestra herramienta y también para extraer base teorica de medidas y posibles líneas futuras de trabajo.

Una  funcionalidad que creo que es destacable en nuestra herramienta es la capacidad de personalizar los valores umbrales de las medidas. Revisando el README del proyecto [**Criticality Score**](https://github.com/ossf/criticality_score) me he encontrado   


`closed_issues_count [0.5 - 5000]  Number of issues closed in the last 90 days `
Indicates high contributor involvement and focus on closing user  issues. Lower weight since it is dependent on project contributors.

Creo que estos umbrales deberían personalizarse.
